version: "3"

vars:
  VERSION: v0.0.1-test

tasks:
  ## ------------------------------------------------------------
  ## Node tasks
  ## ------------------------------------------------------------
  update:local:
    summary: "Update Local xcFramework with newly built xcFramework"
    dir: ../
    cmds:
      - find sonr/build -type d -name "Motor.xcframework" -exec mv '{}' MotorKit/Frameworks/Motor.xcframework \;

  update:buf:
    summary: Update protocol buffers
    dir: ./Sources/MotorKit
    cmds:
      - buf generate buf.build/sonr-io/motor
