// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Motor-Tester",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Motor-Tester",
            targets: ["AppModule"],
            bundleIdentifier: "io.sonr.Motor-Tester",
            teamIdentifier: "S6SPZ444RB",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/sonr-io/MotorKit", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MotorKit", package: "motorkit")
            ],
            path: "."
        )
    ]
)